language: node_js
node_js:
  - "0.10"
  - "4"
  - "5"

sudo: false

env:
  global:
    - PROTRACTOR_BROWSERS=firefox
    - KARMA_BROWSERS=Firefox,PhantomJS

install:
  - npm install

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - grunt test

after_success:
  - grunt coveralls
